-- CLEANUP: REMOVE ALL DATA BEFORE REINSERT
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE DELIVERED';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE DELIVERIES';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE DISH_INGREDIENTS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE DISHES_TO_ORDERS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TABLE_SERVICE';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE REVIEWS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE RESTAURANT_ORDERS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE RESTAURANT_TABLES';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE DISHES';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE INGREDIENTS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE CATEGORIES';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE SUPPLIERS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE WAITERS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMERS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE PEOPLE';
END;
/
